[package]
name = "smt2"
version = "0.1.0"
authors = ["Timothée Haudebourg <timothee.haudebourg@irisa.fr>"]
edition = "2018"

[dependencies]
utf8-decode = "*"
source-span = { path = "/home/timothee/documents/projects/hemisemi/utils/parsing/source-span" }
ena = "*"
